### ISSUE TITLE
Error on M-x magic-buffer

### ISSUE THREAD

**Issue by shanbhardwaj** [sabof/magic-buffer#4]
The following error is thrown on os x 
GNU Emacs 24.2.93.1 (x86_64-apple-darwin12.2.0, Carbon Version 1.6.0 AppKit 1187.34) of 2013-02-2

url-retrieve-internal: Wrong number of arguments: #[(url callback cbargs) "ÄÅ  
#)" [url-gateway-method url callback cbargs tls url-http] 4

**Comment by sabof** [comment]
Can't really help you here. Downloading the repository should make it work. You could also upgrade your emacs, and hope that whatever misalignment there was got fixed.

**Comment by sabof** [comment]
I'd think it got fixed, since this code is probably shared across platforms, and I can download everything without issues.
